AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Boltdir/**/*'
    - 'vendor/**/*'
    - 'vendored/**/*'
    - 'acceptance/vendor/**/*'
    - 'modules/**/*'
    - 'docs/**/*'
    - 'site-modules/**/*'

# Checks for if and unless statements that would fit on one line if written as a
# modifier if/unless.
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# Disable nearly all Metrics checks. These seem better off left to judgement.

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - lib/bolt/transport/local/shell.rb

# Enforce LF line endings, even when on Windows
Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedHashRocketStyle: [key, table]
  EnforcedColonStyle: [key, table]
