inherit_from: .rubocop_todo.yml

plugins: rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - Boltdir/**/*
    - vendor/**/*
    - vendored/**/*
    - acceptance/vendor/**/*
    - modules/**/*
    - docs/**/*
    - site-modules/**/*
    - tasks/**/*
  SuggestExtensions: false
  TargetRubyVersion: 3.0
