# frozen_string_literal: true

##################################################################
## DO NOT EDIT THIS FILE                                        ##
## Use /etc/puppetlabs/plan-executor/conf.d/plan-executor.conf  ##
## to configure the sinatra server                              ##
##################################################################

require 'plan_executor/app'
require 'bolt_server/acl'
require 'plan_executor/config'
require 'bolt/logger'

Bolt::Logger.initialize_logging

config_path = ENV['PLAN_EXECUTOR_CONF'] || '/etc/puppetlabs/plan-executor/conf.d/plan-executor.conf'

config = PlanExecutor::Config.new
config.load_file_config(config_path)
config.load_env_config
config.validate

Logging.logger[:root].add_appenders Logging.appenders.stderr(
  'console',
  layout: Bolt::Logger.default_layout,
  level: config['loglevel']
)

if config['logfile']
  stdout_redirect config['logfile'], config['logfile'], true
end

bind_addr = +"ssl://#{config['host']}:#{config['port']}?"
bind_addr << "cert=#{config['ssl-cert']}"
bind_addr << "&key=#{config['ssl-key']}"
bind_addr << "&ca=#{config['ssl-ca-cert']}"
bind_addr << "&verify_mode=force_peer"
bind_addr << "&ssl_cipher_filter=#{config['ssl-cipher-suites'].join(':')}"
bind bind_addr

impl = PlanExecutor::App.new(config)
unless config['whitelist'].nil?
  impl = BoltServer::ACL.new(impl, config['whitelist'])
end

app impl
