FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY fixtures/scripts/windev/setup.ps1 ./
COPY fixtures/scripts/windev/agent.ps1 ./
RUN powershell ./setup.ps1
RUN powershell ./agent.ps1
CMD ["powershell", "Start-Sleep", "-s 1000000"]
