FROM puppet/puppetdb:6.13.1

# Use our own certs so this doesn't have to wait for puppetserver startup
COPY fixtures/ssl/ca.pem /opt/puppetlabs/server/data/puppetdb/certs/certs/ca.pem
COPY fixtures/ssl/cert.pem /opt/puppetlabs/server/data/puppetdb/certs/certs/pdb.pem
COPY fixtures/ssl/key.pem /opt/puppetlabs/server/data/puppetdb/certs/private_keys/pdb.pem
COPY fixtures/ssl/crl.pem /opt/puppetlabs/server/data/puppetdb/certs/ca/ca_crl.pem
