#!/usr/bin/env ruby
# frozen_string_literal: true

if RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
  require 'bootsnap'
  Bootsnap.setup(
    cache_dir:       File.join(ENV['ProgramData'], 'PuppetLabs', 'bolt'),
    load_path_cache: false
  )
end
require 'bolt'
require 'bolt/cli'

Thread.current[:name] ||= 'main'
cli = Bolt::CLI.new(ARGV)
begin
  opts = cli.parse
  exitcode = cli.execute(opts)
  exit exitcode
rescue Bolt::CLIExit
  exit
rescue Bolt::Error => e
  exit e.error_code
end
