#!/usr/bin/env ruby

require 'bolt'
require 'bolt/cli'

cli = Bolt::CLI.new(ARGV)
begin
  opts = cli.parse
  cli.execute(opts)
rescue Bolt::CLIExit
  exit
rescue Bolt::CLIError => e
  warn e.message
  exit e.error_code
end
