---
topic: project
guide: |
    A Bolt project is a directory that serves as the launching point for Bolt
    and allows you to create a shareable orchestration application. Projects
    typically include a project configuration file, an inventory file, and any
    content you use in your project workflow, such as tasks and plans.

    When you run Bolt, it runs in the context of a project. If the directory you
    run Bolt from is not a project, Bolt attempts to find a project by
    traversing the parent directories. If Bolt is unable to find a project, it
    runs from the default project, located at '~/.puppetlabs/bolt'.

    A directory is only considered a Bolt project when it has a project
    configuration file named 'bolt-project.yaml'. Bolt doesn't load project data
    and content, including inventory files, unless the data and content are part
    of a project.

documentation:
  - https://pup.pt/bolt-projects
  - https://pup.pt/bolt-project-reference
