name: Podman

on:
  push:
    branches: [main]
    paths: ['lib/bolt/config*', 'lib/bolt/executor.rb', 'lib/bolt/transport/podman*', 'spec/**/*/podman_spec.rb']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths: ['lib/bolt/config*', 'lib/bolt/executor.rb', 'lib/bolt/transport/podman*', 'spec/**/*/podman_spec.rb']

jobs:
  podman:
    name: Podman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Pre-test setup
        run: |
          podman build -f spec/Dockerfile -t spec_ubuntu_node
          podman run -d --name ubuntu_node spec_ubuntu_node
          bundle exec r10k puppetfile install
      - name: Run tests with expensive containers
        run: bundle exec rake tests:podman
