config: {}
networks:
- config:
    ipv4.address: auto
    ipv6.address: auto
  description: ""
  name: lxdbr0
  type: ""
  project: default
storage_pools:
- name: storage
  driver: dir
profiles:
- config: {}
  description: ""
  devices:
    root:
      path: /
      pool: storage
      type: disk
  name: default
cluster: null
